#! /bin/sh

##########################
# autostart applications #
##########################

pgrep -x sxhkd > /dev/null || sxhkd &
picom -f &

# generate new application menu file at every login
gen_menufile > /home/phanindra/xmenu/menu

nm-applet &
launchpolybar &
launchxfceclipboard
/usr/lib/xfce4/notifyd/xfce4-notifyd &
nitrogen --restore &
lxsession &
numlockx on
locker &

# hide mouse when not in use
unclutter &

# handles cursor problem
xsetroot -cursor_name left_ptr &


###############################
# monitor and workspace setup #
###############################

bspc monitor VGA1 -d 1 2 3 4 5 6 7

#######################
# bspwm configuration #
#######################

bspc config border_width         2
bspc config window_gap          4
bspc config top_padding     	28
bspc config bottom_padding   	0
bspc config left_padding    	0
bspc config single_monocle  	false
bspc config click_to_focus  	true
bspc config focus_follows_pointer  false

bspc config pointer_modifier 	mod4
bspc config pointer_action1	    move
bspc config pointer_action2	    resize_side
bspc config pointer_action3	    resize_corner
bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     true

##################
# bspwm coloring #
##################

bspc config normal_border_color           "#2e3440"
bspc config active_border_color           "#a3be8c"
bspc config focused_border_color          "#a3be8c"
bspc config presel_feedback_color         "#4c566a"
bspc config urgent_border_color 	      "#bf616a"


###############
# bspwm rules #
###############

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a "Brave-browser" desktop='^2'
bspc rule -a Spotify desktop='^3'
bspc rule -a Gnome-calculator state=floating follow=on
bspc rule -a Audacious state=floating follow=off
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a zoom desktop='^4' state=floating follow=on
bspc rule -a vlc desktop='^6' follow=on
bspc rule -a Viewnior state=floating follow=on
bspc rule -a Transmission-gtk state=floating follow=on desktop='^7'
bspc rule -a Mousepad state=floating
bspc rule -a Lxappearance state=floating
bspc rule -a Sxiv state=floating
bspc rule -a Engrampa state=floating
bspc rule -a stacer state=floating
bspc rule -a Anki state=floating
