;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
;;
;;	    ____        __      __
;;	   / __ \____  / /_  __/ /_  ____ ______
;;	  / /_/ / __ \/ / / / / __ \/ __ `/ ___/
;;	 / ____/ /_/ / / /_/ / /_/ / /_/ / /
;;	/_/    \____/_/\__, /_.___/\__,_/_/
;;	              /____/
;;
;; Created By Aditya Shakya @adi1090x
;;
;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[color]

bg = #2e3440
bg-alt = #3b4252
fg = #eceff4
fg-alt = #4C566A

accent = #5e81ac
orange = #d08770
green = #a3be8c
yellow = #ebcb8b
purpul = #b48ead
red = #bf616a
cyan = #88c0d0

;==========================================================

[bar/main]
width = 100%
height = 32
bottom = false
radius = 0
fixed-center = false
line-size = 3
border-size = 0
module-margin-right = 1

tray-position = right
tray-background = ${color.bg}
tray-padding = 2

wm-restack = bspwm

background = ${color.bg}
foreground = ${color.fg}

;==========================================================

font-0 = "Mononoki:pixelsize=10;3"
font-1 = "Iosevka Nerd Font:size=13;4"
font-2 = "Font Awesome 5:size=13;5"


;==========================================================

enable-ipc = true
cursor-click = pointer

scroll-up = bspwm-wsnext
scroll-down = bspwm-wsprev

;== Module Location ========================================================

modules-left = bspwm xwindow
modules-right = pkg network cputemp memory cpuload volume time
;== Modules ========================================================

[module/menu]
type = custom/text
content = 

content-background = ${color.bg}
content-foreground = ${color.fg}
content-padding = 1

click-left = /home/phanindra/xmenu/xmenu.sh

[module/xwindow]
type = internal/xwindow
format = <label>
format-background = ${color.bg}
format-foreground = ${color.fg}
format-padding = 1

label = %title%
label-maxlen = 40

[module/bspwm]
type = internal/bspwm
enable-click = true
enable-scroll = true
format = <label-state>
reverse-scroll = true

ws-icon-0 = 1;
ws-icon-1 = 2;
ws-icon-2 = 3;
ws-icon-3 = 4;
ws-icon-4 = 5;
ws-icon-5 = 6;
ws-icon-6 = 7;
ws-icon-7 = 8;

label-focused = %icon%
label-focused-foreground = ${color.bg}
label-focused-background = ${color.accent}
label-focused-underline = ${color.bg}
label-focused-overline = ${color.bg}
label-focused-padding = 1

label-occupied = %icon%
label-occupied-forground = ${color.fg}
label-occupied-underline = ${color.bg}
label-occupied-overline = ${color.bg}
label-occupied-padding = 1

label-urgent = %icon%
label-urgent-forground = ${color.red}
label-urgent-underline = ${color.bg}
label-urgent-overline = ${color.bg}
label-urgent-padding = 1

label-empty = %icon%
label-empty-padding = 1
label-empty-foreground = ${color.fg-alt}
label-empty-underline = ${color.bg}
label-empty-overline = ${color.bg}

;==========================================================

[module/pkg]
type = custom/script
exec = ~/.config/polybar/scripts/updates.sh

format-underline = ${color.bg}
format-overline = ${color.bg}

format-prefix = 
format-prefix-padding = 1
format-prefix-background = ${color.cyan}
format-prefix-foreground = ${color.bg}

label-background = ${color.bg-alt}
label-padding = 1

tail = true

[module/cputemp]
type = custom/script
exec = cputemp.py
interval = 2

format-prefix = ""
format-prefix-background = ${color.red}
format-prefix-padding = 1
format-prefix-foreground = ${color.bg}

format-underline = ${color.bg}
format-overline = ${color.bg}

label = %output%
label-padding = 1
label-background = ${color.bg-alt}


[module/cpuload]
type = custom/script
exec = cpuload.py
interval = 3

format-underline = ${color.bg}
format-overline = ${color.bg}

format-prefix-background = ${color.cyan}
format-prefix-foreground = ${color.bg}
format-prefix-padding = 1
format-prefix = ""

label = %output%%
label-padding = 1
label-background = ${color.bg-alt}

[module/memory]
type = custom/script
exec = mem_usage.py
interval = 2

format-underline = ${color.bg}
format-overline = ${color.bg}

format-prefix-background = ${color.purpul}
format-prefix-foreground = ${color.bg}
format-prefix-padding = 1
format-prefix = ""

label = %output%
label-padding = 1
label-background = ${color.bg-alt}

[module/volume]
type = internal/alsa
master-mixer = Master

format-volume = <ramp-volume><label-volume>
format-volume-overline = ${color.bg}
format-volume-underline = ${color.bg}

format-muted = <label-muted>
format-muted-prefix = "婢"
format-muted-prefix-background = ${color.green}
format-muted-prefix-foreground = ${color.bg}
format-muted-prefix-padding = 1
format-muted-underline = ${color.bg}
format-muted-overline = ${color.bg}


label-volume = %percentage%%
label-volume-background = ${color.bg-alt}
label-volume-foreground = ${color.fg}
label-volume-padding = 1

label-muted = "Muted"
label-muted-background = ${color.bg-alt}
label-muted-foreground = ${color.fg}
label-muted-padding = 1


ramp-volume-0 = 奄
ramp-volume-1 = 奄
ramp-volume-2 = 奔
ramp-volume-3 = 奔
ramp-volume-4 = 墳
ramp-volume-5 = 墳
ramp-volume-6 = 墳
ramp-volume-padding = 1
ramp-volume-background = ${color.green}
ramp-volume-foreground = ${color.bg}

[module/time]
type = internal/date

interval = 1.0
time = %H:%M

date-alt = %a, %d %b %Y

format = <label>
format-underline = ${color.bg}
format-overline = ${color.bg}

format-prefix = 
format-prefix-background = ${color.yellow}
format-prefix-foreground = ${color.bg}
format-prefix-padding = 1

label = %time%%date%
label-background = ${color.bg-alt}
label-padding = 1

[module/network]
type = internal/network

interface = enp2s0

interval = 3.0

accumulate-stats = true
unknown-as-up = true

format-connected = <label-connected>
format-connected-prefix = 龍
format-connected-prefix-background = ${color.orange}
format-connected-prefix-foreground = ${color.bg}
format-connected-prefix-padding = 1
format-connected-overline = ${color.bg}
format-connected-underline = ${color.bg}

label-connected =  %downspeed% 祝 %upspeed%
label-connected-foreground = ${color.fg}
label-connected-background = ${color.bg-alt}
label-connected-padding = 1

label-disconnected = "not connected"
label-disconnected-foreground = ${color.fg}
label-disconnected-background = ${color.bg-alt}

;== EOF ========================================================
